//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logamoasta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lagerverlauf
    {
        public int VID { get; set; }
        public int ArtikelNr { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Einkaufspreis { get; set; }
        public decimal Verkaufspreis { get; set; }
        public int Anzahl { get; set; }
        public int Benutzer { get; set; }
    }
}
